version: '3.9'
services:
  back:
    image: node:16
    env_file:
      - ./back/.env
    volumes:
      - ./back:/app
    working_dir: /app
    ports:
      - 3000:3000
    command: sh -c 
      "npm install &&
       npm install -g nest &&
       npm run start:dev"
  documents_main:
    image: node:16
    volumes:
      - ./main-service:/app
    working_dir: /app
    ports:
      - 3001:3001
    command: sh -c 
      "npm install &&
       npm install -g nest &&
       npm run start:dev"
  redis:
    image: redis