version: '3.9'
services:
  back:
    image: node:16
    env_file:
      - ./back/.env
    volumes:
      - ./back:/app
    working_dir: /app
    ports:
      - 3000:3000
    command: sh -c "npm install &&
       npm install -g @nestjs/cli &&
       npm run start:dev"
  video_consumer:
    build: ./video-consumer
    # env_file:
    #   - ./video-consumer/.env
    volumes:
      - ./video-consumer/nest-service:/app
    working_dir: /app
    command: sh -c "
       python3.9 /python_script/setup.py &
       npm install &&
       npm install -g @nestjs/cli &&
       npm run start:dev"
  kibana:
    image: docker.elastic.co/kibana/kibana:8.1.0
    ports:
      - "5601:5601"
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    links:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.0
    ports:
      - "9200:9200"
    environment:
      xpack.security.enabled: "false"
      logger.restcontroller.level:  error
      discovery.type: single-node
    volumes:
      - esdata1:/usr/share/elasticsearch/data
  redis:
    image: redis


volumes:
  esdata1:
    driver: local