version: '3.9'
services:
  back:
    image: node:16
    env_file:
      - ./back/.env
    volumes:
      - ./back:/app
    working_dir: /app
    ports:
      - 3000:3000
    command: sh -c 
      "npm install &&
       npm install -g @nestjs/cli &&
       npm run start:dev"
  documents_main:
    image: node:16
    volumes:
      - ./main-service:/app
    working_dir: /app
    ports:
      - 3001:3001
    command: sh -c 
      "npm install &&
       npm install -g @nestjs/cli &&
       npm run start:dev"
  video_consumer:
    build: ./video-consumer
    env_file:
      - ./video-consumer/.env
    volumes:
      - ./video-consumer/nest-service:/app
    working_dir: /app
    command: sh -c 
      "
       python3.9 /python_script/setup.py &
       npm install &&
       npm install -g @nestjs/cli &&
       npm run start:dev
       "
  redis:
    image: redis